// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
//

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-vsphere-migrating-cns-vols-between-datastores_{context}"]
= Migrating CNS volumes between datastores for vSphere

[role="_abstract"]
To optimize storage performance or free up capacity, you can migrate vSphere Cloud Native Storage (CNS) volumes between datastores without data loss.

If you are running out of space in your current datastore, or want to move to a more performant datastore, you can migrate VMware CNS volumes between datastores. This applies to both attached and detached volumes.

== Limitations
* Requires VMware vSphere 8.0.2 or later, or VMware vSphere Foundation (VVF) 9, or VMware Cloud Foundation (VCF) 9

* Only one volume can be migrated at a time.

* RWX volumes are not supported.

* CNS volume should only be migrated to a datastore that is shared with all hosts that make up the {product-title} cluster.

* Migrating volumes between different datastore in different datacenters is not supported.

* VMware HCX is not supported.

== Additional limitations
For additional limitations, see _For vSphere 8_, _For VCF 9_, _For vSphere v8.0, more general information_, and _For VCF 9, more general information_ under _Additional resources_.

