//
// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-azure.adoc
//

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-azure-disk-overview_{context}"]
= Overview

[role="_abstract"]
{product-title} is capable of provisioning persistent volumes (PVs) using the Container Storage Interface (CSI) driver for Microsoft Azure Disk Storage.

Familiarity with persistent storage and configuring CSI volumes is recommended when working with a CSI Operator and driver. For more information about these topics, see _Understanding persistent storage_ and _Configuring CSI volumes_ under _Additional resources_.

To create CSI-provisioned PVs that mount to Azure Disk storage assets, {product-title} installs the Azure Disk CSI Driver Operator and the Azure Disk CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

* The _Azure Disk CSI Driver Operator_ provides a storage class named `managed-csi` that you can use to create persistent volume claims (PVCs). The Azure Disk CSI Driver Operator supports dynamic volume provisioning by allowing storage volumes to be created on-demand, eliminating the need for cluster administrators to pre-provision storage. You can disable this default storage class if desired (see _Managing the default storage class_ under _Additional resources_).

* The _Azure Disk CSI driver_ enables you to create and mount Azure Disk PVs.

[NOTE]
====
{product-title} provides automatic migration for the Azure Disk in-tree volume plugin to its equivalent CSI driver. For more information, see _CSI automatic migration_ under _Additional resources_.
====