// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent_storage-csi-stack-hub.adoc
//

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-azure-stack-hub-overview_{context}"]
= Overview

[role="_abstract"]
{product-title} is capable of provisioning persistent volumes (PVs) using the Container Storage Interface (CSI) driver for Azure Stack Hub Storage. Azure Stack Hub, which is part of the Azure Stack portfolio, allows you to run apps in an on-premise environment and deliver Azure services in your datacenter.

Familiarity with persistent storage and configuring CSI volumes is recommended when working with a CSI Operator and driver. For more information, see _Understanding persistent volumes_ and _Configuring CSI volumes_ under _Additional resources_.

To create CSI-provisioned PVs that mount to Azure Stack Hub storage assets, {product-title} installs the Azure Stack Hub CSI Driver Operator and the Azure Stack Hub CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

* The _Azure Stack Hub CSI Driver Operator_ provides a storage class (`managed-csi`), with "Standard_LRS" as the default storage account type, that you can use to create persistent volume claims (PVCs). The Azure Stack Hub CSI Driver Operator supports dynamic volume provisioning by allowing storage volumes to be created on-demand, eliminating the need for cluster administrators to pre-provision storage.

* The _Azure Stack Hub CSI driver_ enables you to create and mount Azure Stack Hub PVs.
