// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-group-snapshots.adoc

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-group-snapshots-limitations_{context}"]
= CSI volume group snapshots limitations

[role="_abstract"]
Volume group snapshots have operational and consistency limitations that affect how you can use them for data protection and recovery. Understanding these constraints helps you design appropriate backup and recovery strategies for multi-volume applications.

Volume group snapshots has the following limitations:

* Does not support reverting an existing persistent volume claim (PVC) to an earlier state represented by a snapshot It only supports provisioning a new volume from a snapshot.

* No guarantees of application consistency, for example, crash consistency, are provided beyond those provided by the storage system. For more information about application consistency, see _Quiesce and Unquiesce Hooks_ under _Additional resources_.