// Module included in the following assemblies:
//
// * storage/understanding-persistent-storage.adoc
//* microshift_storage/understanding-persistent-storage-microshift.adoc

:_mod-docs-content-type: PROCEDURE
[id="using_selinuxChangePolicy_testing-mountoption-rwo-rwx_{context}"]
= Testing the RWO and RWX and SELinux mount option feature

[role="_abstract"]
The SELinux mount option applies the correct security context during mount without recursive relabeling, reducing pod startup times on volumes with many files. In {product-title} 4.21, you can evaluate the mount option feature for RWO and RWX volumes as a Technology Preview feature.

:FeatureName: RWO/RWX SELinux mount
include::snippets/technology-preview.adoc[]

.Procedure

* Enable Feature Gates. For information about enabling Feature Gates, see _Section Enabling features using feature gates_.
+
RWO and RWX volumes now have mount option as the default behavior.

.Next step
Carefully test your applications and observe how they are using storage. Consult this article _SELinux-related conflicts Knowledge Base article_ under the _Additional resources_ section, and consider opting out from using mount option if you are experiencing issues. See Section _Opting out of the SELinux mount option default_.